### ISSUE TITLE
[TASK]: Link terarium.ai to production environment

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/orchestration#1]
**Describe the task**
Contact CloudOPS department to set:
* https://terarium.ai for the product website
* https://app.terarium.ai our production environment.
* https://staging.terarium.ai/ as our staging environment

**Task Items**
- [ ] https://terarium.ai is available to the users
- [x] https://app.terarium.ai is available to users
- [x] https://staging.terarium.ai is available to users

**Goal**
All TERArium endpoints are available

**Comment by YohannParis** [comment]
@dgauldie should we use a subdomain name https://staging.terarium.ai as our **staging** environment?

**Comment by dgauldie** [comment]
This is now complete
