### ISSUE TITLE
[TASK]: Setup CI pipelines

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/orchestration#9]
**Describe the task**
* Setup deployment script into the `orchestration` repo for easier management.
* Setup automatisation to deploy repo to GitHub Packages as containers.
* Create AWS environment.
* Setup CI pipelines for each deployment (_local_, _staging_, and _production_.).
* Can use [_Ansible_](https://www.ansible.com/) or [_HELM_](https://helm.sh/).

**Task Items**
- [ ] Move all k8 deployment scripts off every repo to `orchestration`.
- [ ] Create different scripts for each deployment.
- [ ] Setup _staging_ and _production_ CI pipelines to deploy GitHub Packages containers to AWS.
- [ ] Write complete documentation for each steps of each deployments.

**Goal**
* _staging_ and _production_ pipeline should run automatically on any GitHub Packages container.
* The local deployment script should be easily use by a random dev to have the full TERArium application up and running on their own machine
